# Generated by Django 4.2.2 on 2023-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
